### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ShalokShalom**
correct typos

### CODE REVIEW

**Comment by stdgregwar** [comment]
Will merge but pay attention that this readme is Slightly outdated anyway.

**Comment by ShalokShalom** [comment]
In which way?

**Comment by stdgregwar** [comment]
Some of the features marked as non-working. Like 'lift' or others. Are actually implemented.

**Comment by ShalokShalom** [comment]
You might be able to fix this.
There is one more eneemies as well, while I cant edit currently on this phone.

**Pull request merged**
